export function getTargetBitrateForVideoResolution(
  videoWidth: number,
  videoHeight: number,
  isHighFramerate = false
) {
  // Rough equation generated by mapping the number of square pixels in various
  // resolutions to the recommended Mbps bitrates for those resolutions:
  // target bitrate = 0.0000216066 * (square pixels for video resolution)^0.8924542
  const targetBitrate =
    0.0000216066 *
    Math.pow(videoWidth * videoHeight, 0.8924542) *
    // If the video has a high framerate, multiply the bitrate by 1.5Mbps
    (isHighFramerate ? 1.5 : 1);

  return Math.round(targetBitrate * 100) / 100;
}
