import * as findCacheDir from "find-cache-dir";
import { promises as fsPromises } from "fs";
import * as path from "path";

export const cacheDirectory = findCacheDir({
  name: "web-video-loader",
  create: true,
});

/**
 * Takes an array of all files that were generated by the loader
 * and removes any dead files from the cache
 */
export async function cleanUpCache(builtCacheFilePaths: string[]) {
  if (!cacheDirectory) return;

  const allCachedFileNames = await fsPromises.readdir(cacheDirectory);

  return Promise.all(
    allCachedFileNames.map((cachedFileName) => {
      if (!builtCacheFilePaths.includes(cachedFileName.replace(".gz", ""))) {
        return fsPromises.unlink(path.resolve(cacheDirectory, cachedFileName));
      }
    })
  );
}
